name: 部署gh-pages


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SECRET: ${{secrets.COMMIT_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true
      - name: 安装依赖
        working-directory: './gh-page'
        run: npm install
      - name: 编译html
        working-directory: './gh-page'
        run: npm run generate:gh-pages


